filebrowser/urls.py
# As of version 3.4, all urls moved to FileBrowserSite class in filebrowser.sites

filebrowser/models.py
# This file is only necessary for the tests to work

filebrowser/forms.py
# coding: utf-8

# PYTHON IMPORTS
import re, os

# DJANGO IMPORTS
from django import forms
from django.forms.formsets import BaseFormSet
from django.utils.translation import ugettext_lazy as _

# FILEBROWSER IMPORTS
from filebrowser.settings import MAX_UPLOAD_SIZE, FOLDER_REGEX
from filebrowser.functions import convert_filename

alnum_name_re = re.compile(FOLDER_REGEX, re.U)


# CHOICES
TRANSPOSE_CHOICES = (
    ("", u"-----"),
    ("0", _(u"Flip horizontal")),
    ("1", _(u"Flip vertical")),
    ("2", _(u"Rotate 90° CW")),
    ("4", _(u"Rotate 90° CCW")),
    ("3", _(u"Rotate 180°")),
)


class CreateDirForm(forms.Form):
    """
    Form for creating a folder.
    """
    
    def __init__(self, path, *args, **kwargs):
        self.path = path
        self.site = kwargs.pop("filebrowser_site", None)
        super(CreateDirForm, self).__init__(*args, **kwargs)
        
    name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['name'])


class ChangeForm(forms.Form):
    """
    Form for renaming a file/folder.
    """
    
    custom_action = forms.ChoiceField(label=_(u'Actions'), required=False)
    name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def __init__(self, *args, **kwargs):
        self.path = kwargs.pop("path", None)
        self.fileobject = kwargs.pop("fileobject", None)
        from filebrowser.sites import site
        self.site = kwargs.pop("filebrowser_site", None)
        super(ChangeForm, self).__init__(*args, **kwargs)
        
        # Initialize choices of custom actions 
        choices = [("",u"-----"),]
        
        for name, action in self.site.applicable_actions(self.fileobject):
            choices.append((name, action.short_description))
        
        self.fields['custom_action'].choices=choices

    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif self.site.storage.isfile(os.path.join(self.path, convert_filename(self.cleaned_data['name'])))  and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])

filebrowser/views.py
# As of version 3.4, all views moved to FileBrowserSite class in filebrowser.sites

filebrowser/templates/filebrowser/createdir.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags fb_csrf admin_static %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}
{% block coltype %}flex{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form action="{% query_string '' 'p' %}" method="post">{% fb_csrf_token %}
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="module aligned">
            <div class="form-row {% if form.dir_name.errors %}errors{% endif %}">
                <div>
                    <label class="required" for="id_dir_name">{{ form.name.label }}</label>
                    {{ form.name }}
                    {% if form.dir_name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
                    <p class="help">
                        {{ form.name.help_text|safe }}
                        {% if settings_var.NORMALIZE_FILENAME or settings_var.CONVERT_FILENAME %}
                            <br />
                            {% if settings_var.NORMALIZE_FILENAME %}
                                {% trans "The Name will be normalized by converting or stripping all non-standard characters." %} <br />
                            {% endif %}
                            {% if settings_var.CONVERT_FILENAME %}
                                {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
            </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="{% trans 'Submit' %}" class="default" />
        </dib>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/custom_field.html
{% load i18n fb_versions %}
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField" name="{{ final_attrs.name }}" value="{{ value.path }}" /><a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{{ url }}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory|urlencode|urlencode }}{% endif %}{% if final_attrs.format %}&amp;type={{ final_attrs.format }}{% endif %}');" class="fb_show"></a>
{% if value.filetype == "Image" %}
{% version_object value.path final_attrs.ADMIN_THUMBNAIL as thumbnail_version %}
{% if thumbnail_version %}
<p class="preview" id="preview_{{ final_attrs.id }}">
    <a href="{{ value.url }}" target="_blank" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" src="{{ thumbnail_version.url }}" class="preview" />
    </a>
</p>
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% if value and not value.exists %}
<ul class="errorlist"><li>{% trans "File not found" %}</li></ul>
{% endif %}

filebrowser/templates/filebrowser/delete_confirm.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags fb_versions admin_static %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
    {{ block.super }}
    {{ media }}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <form>
        <fieldset class="module collapse open">
            <h2>{% blocktrans with fileobject.filename as escaped_object %}Are you sure you want to delete "{{ escaped_object }}"? All of the following items will be deleted:{% endblocktrans %}</h2>
            <div class="form-row">
                <div>
                    {{ fileobject.filename }}
                </div>
            </div>
            {% if filelisting %}
                <div class="form-row">
                    {% for item in filelisting %}
                        {{ item.path_relative_directory }}
                    {% endfor %}
                </div>
            {% endif %}
            {% if additional_files %}
                <div class="form-row">
                    {% blocktrans with additional_files as escaped_object %}... and {{ escaped_object }} more Files.{% endblocktrans %}
                </div>
            {% endif %}
        </fieldset>
        <div class="submit-row">
            <p class="deletelink-box">
                <a href="{% url filebrowser:fb_detail %}{% query_string %}" class="deletelink">{% trans "Cancel" %}</a>
            </p>
            <a href="{% url filebrowser:fb_delete %}{% query_string %}" class="button default">{% trans "Yes, I'm sure" %}</a>
        </div>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/detail.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load i18n adminmedia fb_tags fb_versions admin_static %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript">
    (function($){
        $(document).ready(function() {
            $("div#content .collapse").grp_collapsible({
                on_init: function(elem, options) {
                    // open collapse (and all collapse parents) in case of errors
                    if (elem.find("ul.errorlist").length > 0) {
                        elem.removeClass("closed")
                            .addClass("open");
                        elem.parents(".collapse")
                            .removeClass("closed")
                            .addClass("open");
                    }
                }
            });
        });
    })(django.jQuery);
    </script>
    {{ media }}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div class="content-main">
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">{% csrf_token %}
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="module aligned">
            <div class="form-row {% if form.name.errors %}errors{% endif %}">
                <div>
                    {% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
                    <label class="required" for="id_name">{{ form.name.label }}</label>
                    {{ form.name }}
                    {% if form.name.help_text %}<p class="help">{{ form.name.help_text|safe }}</p>{% endif %}
                </div>
            </div>
        </fieldset>
        {% if fileobject.filetype == "Image" %}
        <fieldset class="module collapse open">
            <h2 class="collapse-handler">{% trans "Edit" %}</h2>
            <div class="form-row {% if form.custom_action.errors %}errors{% endif %}">
                <div>
                    {% if form.custom_action.errors %}<ul class="errorlist">{{ form.custom_action.errors }}</ul>{% endif %}
                    <label class="required" for="id_custom_action">{{ form.custom_action.label }}</label>
                    {{ form.custom_action }}
                    {% if form.custom_action.help_text %}<p class="help">{{ form.custom_action.help_text|safe }}</p>{% endif %}
                </div>
            </div>
        </fieldset>
        {% endif %}
        {% if fileobject.filetype == "Folder" %}
        <fieldset class="module collapse open">
            <h2 class="collapse-handler">{% trans "Folder Information" %}</h2>
            <div class="form-row">
                <div class="column span-4"><label>{% trans "Date" %}</label></div>
                <div class="column span-flexible">
                    <p class="readonly">
                        {{ fileobject.datetime|date:"N j, Y" }}
                    </p>
                </div>
            </div>
        </fieldset>
        {% endif %}
        {% if fileobject.filetype != "Folder" %}
        <fieldset class="module collapse open">
            <h2 class="collapse-handler">{% trans "File Information" %}</h2>
            <div class="form-row">
                <div class="column span-4"><label>{% trans "URL" %}</label></div>
                <div class="column span-flexible">
                    <p class="readonly">
                        <a href="{{ fileobject.url }}">{{ fileobject.url }}</a>
                    </p>
                </div>
            </div>
            <div class="form-row">
                <div class="column span-4"><label>{% trans "Filesize" %}</label></div>
                <div class="column span-flexible">
                    <p class="readonly">
                        {{ fileobject.filesize|filesizeformat }}
                    </p>
                </div>
            </div>
            <div class="form-row">
                <div class="column span-4"><label>{% trans "Date" %}</label></div>
                <div class="column span-flexible">
                    <p class="readonly">
                        {{ fileobject.datetime|date:"N j, Y" }}
                    </p>
                </div>
            </div>
            {% if fileobject.filetype == "Image" %}
                <div class="form-row">
                    <div class="column span-4"><label>{% trans "Size" %}</label></div>
                    <div class="column span-flexible">
                        <p class="readonly">
                            {{ fileobject.width }} x {{ fileobject.height }} px
                        </p>
                    </div>
                </div>
            {% endif %}
        </fieldset>
        {% endif %}
        {% if fileobject.filetype == "Image" %}
        <fieldset class="module collapse closed">
            <h2 class="collapse-handler">{% trans "Image Versions" %}</h2>
            {% if settings_var.ADMIN_THUMBNAIL %}
            <div class="form-row">
                <div class="column span-4"><label>{% trans "Thumbnail" %}</label></div>
                <div class="column span-flexible">
                    <img src="{% version fileobject.path settings_var.ADMIN_THUMBNAIL %}" title="{% trans 'View Image' %}" />
                </div>
            </div>
            {% endif %}
            {% if settings_var.ADMIN_VERSIONS %}
                {% for version in settings_var.ADMIN_VERSIONS %}
                    {% version_object fileobject version as image_version %}
                    {% version_setting version %}
                    <div class="form-row">
                        <div class="column span-4"><label>{{ version_setting.verbose_name }}</label></div>
                        <div class="column span-flexible">
                            <img src="{{ image_version.url }}" />
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </fieldset>
        {% endif %}
        <div class="submit-row">
            <input type="submit" value="{% trans 'Save' %}" class="default" />
            <p class="deletelink-box">
                <a href="{% url filebrowser:fb_delete_confirm %}{% query_string %}" class="deletelink">{% trans "Delete" %}</a>
            </p>
            <input type="submit" value="{% trans 'Save and continue editing' %}" name="_continue" />
        </div>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/include/_response.html
{{ response }}

filebrowser/templates/filebrowser/include/breadcrumbs.html
{% load i18n fb_tags %}

<div class="breadcrumbs">
    {% if not query.pop %}
        <a href="../../">{% trans "Home" %}</a> &rsaquo;
    {% endif %}
    {% if breadcrumbs or breadcrumbs_title %}
        <a href="{% url filebrowser:fb_browse %}{% query_string "" "q,dir,filename,p" %}">{% trans 'FileBrowser' %}</a> &rsaquo;
    {% else %}
        {% trans 'FileBrowser' %}
    {% endif %}
    {% for item in breadcrumbs %}
        {% if not forloop.last %}
            <a href="{% url filebrowser:fb_browse %}{% query_string "" "q,dir,filename,p" %}&amp;dir={{ item.1|urlencode }}">{{ item.0 }}</a> &rsaquo;
        {% else %}
            {% if breadcrumbs_title %}
                <a href="{% url filebrowser:fb_browse %}{% query_string "" "q,dir,filename,p" %}&amp;dir={{ item.1|urlencode }}">{{ item.0 }}</a> &rsaquo;
            {% else %}
                {{ item.0 }}
            {% endif %}
        {% endif %}
    {% endfor %}
    {% if breadcrumbs_title %}{{ breadcrumbs_title }}{% endif %}
</div>

filebrowser/templates/filebrowser/include/filelisting.html
{% load i18n adminmedia fb_tags fb_versions %}

{% for fileobject in page.object_list %}

    <!-- THUMBNAIL-VERSION FOR IMAGE-OBJECT -->
    {% if fileobject.filetype == "Image" %}
        {% version_object fileobject settings_var.ADMIN_THUMBNAIL as thumbnail_version %}
    {% endif %}

    <tr class="{% cycle 'row1' 'row2' %}{% if fileobject.filetype == "Folder" %} fb_folder{% endif %}">

        <!-- FILESELECT FOR FILEBROWSEFIELD -->
        {% if query.pop == "1" %}
            <td class="fb_icon">
                {% selectable fileobject.filetype query.type %}
                {% if selectable %}
                    <!-- select original -->
                    <button class="button fb_selectlink" onclick="FileSubmit('{{ fileobject.path }}', '{{ fileobject.url }}', '{{ thumbnail_version.url }}', '{{ fileobject.filetype }}');">{% trans "Select" %}</button>
                    <br/>
                    <!-- select versions -->
                    {% if fileobject.filetype == "Image" and settings_var.ADMIN_VERSIONS %}
                        <div class="pulldown-versions-container">
                            <a href="javascript://" class="pulldown-versions-handler" title="{% trans "Versions" %}">&nbsp;</a>
                            <ul class="pulldown-versions">
                                {% for version in settings_var.ADMIN_VERSIONS %}
                                    {% version_setting version %}
                                    <li{% if forloop.last %} class="last"{% endif %}><a href="{% url filebrowser:fb_version %}{% query_string '' 'filename' %}&amp;filename={{ fileobject.filename|urlencode }}&amp;version={{ version }}" title="">{{ version_setting.verbose_name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% else %}
                    &nbsp;
                {% endif %}
            </td>
        {% endif %}

        <!-- FILESELECT FOR RTE/TINYMCE -->
        <!-- we need to use the absolute url here -->
        {% if query.pop == "2" %}
            <td class="fb_icon">
                {% selectable fileobject.filetype query.type %}
                {% if selectable %}
                    <!-- select original -->
                    <button class="button fb_selectlink" onclick="FileBrowserDialogue.fileSubmit('{{ fileobject.url|escapejs }}');">{% trans "Select" %}</button>
                    <br/>
                    <!-- select versions -->
                    {% if fileobject.filetype == "Image" and settings_var.ADMIN_VERSIONS %}
                        <div class="pulldown-versions-container">
                            <a href="javascript://" class="pulldown-versions-handler" title="{% trans "Versions" %}">&nbsp;</a>
                            <ul class="pulldown-versions">
                                {% for version in settings_var.ADMIN_VERSIONS  %}
                                    {% version_setting version %}
                                    <li{% if forloop.last %} class="last"{% endif %}><a href="{% url filebrowser:fb_version %}{% query_string '' 'filename' %}&amp;filename={{ fileobject.filename|urlencode }}&amp;version={{ version }}" title="">{{ version_setting.verbose_name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% else %}
                    &nbsp;
                {% endif %}
            </td>
        {% endif %}

        <!-- FILESELECT FOR CKEDITOR -->
        {% if query.pop == "3" %}
            <td class="fb_icon">
                {% selectable fileobject.filetype query.type %}
                {% if selectable %}
                <!-- select original -->
                <button class="button fb_selectlink" onclick="OpenFile(ProtectPath('{{ fileobject.url|escapejs }}'));return false;">{% trans "Select" %}</button>
                <br/>
                <!-- select versions -->
                {% if fileobject.filetype == "Image" and settings_var.ADMIN_VERSIONS %}
                    <div class="pulldown-versions-container">
                        <a href="javascript://" class="pulldown-versions-handler" title="{% trans "Versions" %}">&nbsp;</a>
                        <ul class="pulldown-versions">
                            {% for version in settings_var.ADMIN_VERSIONS  %}
                                {% version_setting version %}
                                <li{% if forloop.last %} class="last"{% endif %}><a href="" title="" onclick="OpenFile(ProtectPath('{% version fileobject version %}'));return false;">{{ version_setting.verbose_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% else %}
                    &nbsp;
                {% endif %}
            </td>
        {% endif %}

        <!-- FILEICON -->
        <td>
            {% if fileobject.filetype %}
                <span class="fb_type {{ fileobject.filetype|lower }}">{% trans fileobject.filetype %}</span>
            {% else %}
                <span class="fb_type none">&mdash;</span>
            {% endif %}
        </td>

        <!-- THUMBNAIL -->
        <td class="fb_thumbnail">
            {% if fileobject.filetype == "Image" %}
                <a href="{{ fileobject.url }}" class="fb_viewlink"><img src="{{ thumbnail_version.url }}" title="{% trans 'View Image' %}" /></a>
            {% endif %}
        </td>

        <!-- FILENAME/DIMENSIONS -->
        {% if fileobject.filetype == "Folder" %}
            <td><a href="{% url filebrowser:fb_browse %}{% query_string "" "q,dir,p" %}&amp;dir={{ fileobject.directory|urlencode }}"><strong>{{ fileobject.filename }}</strong></a></td>
        {% else %}
            <td>
                <strong>{{ fileobject.filename }}</strong>
                {% if fileobject.dimensions %}
                    <br /><span class="small">{{ fileobject.dimensions.0 }} x {{ fileobject.dimensions.1 }} px</span><br clear="all" />
                {% endif %}
            </td>
        {% endif %}

        <!-- FOLDER -->
        {% if query.q and settings_var.SEARCH_TRAVERSE %}
            <td><a href="{% url filebrowser:fb_browse %}{% query_string "" "dir,p" %}&amp;dir={{ fileobject.folder|urlencode }}"><strong>{{ fileobject.folder }}</strong></a></td>
        {% endif %}

        <!-- SIZE -->
        <td><span class="small">{% if fileobject.filesize %}{{ fileobject.filesize|filesizeformat }}{% else %}&mdash;{% endif %}</span></td>

        <!-- DATE -->
        <td><span class="small">{{ fileobject.datetime|date:"N j, Y" }}</span></td>

        <!-- EDIT -->
        <td>
            <a href="{% url filebrowser:fb_detail %}{% query_string "" "p" %}&amp;filename={{ fileobject.filename|urlencode }}"><strong>{% trans "Change" %}</strong></a>
        </td>

    </tr>
{% endfor %}

filebrowser/templates/filebrowser/include/filter.html
{% load i18n fb_tags %}
<div id="changelist-filter">
    <h2>{% trans 'Filter' %}</h2>
    <h3>{% trans "By Date" %}</h3>
    <ul>
        <li{% if not query.filter_date %} class="selected"{% endif %}><a href="{% query_string "" "filter_date,p" %}">{% trans "Any Date" %}</a></li>
        <li{% if query.filter_date == "today" %} class="selected"{% endif %}><a href="{% query_string "" "filter_date,p" %}&amp;filter_date=today">{% trans "Today" %}</a></li>
        <li{% if query.filter_date == "past7days" %} class="selected"{% endif %}><a href="{% query_string "" "filter_date,p" %}&amp;filter_date=past7days">{% trans "Past 7 days" %}</a></li>
        <li><a href="{% query_string "" "filter_date,p" %}&amp;filter_date=thismonth"></a></li>
        <li{% if query.filter_date == "thismonth" %} class="selected"{% endif %}><a href="">{% trans "This Month" %}</a></li>
        <li{% if query.filter_date == "thisyear" %} class="selected"{% endif %}><a href="{% query_string "" "filter_date,p" %}&amp;filter_date=thisyear">{% trans "This year" %}</a></li>
    </ul>

    <h3>{% trans "By Type" %}</h3>
    <ul>
        <li{% if not query.filter_type %} class="selected"{% endif %}><a href="{% query_string "" "filter_type,p" %}">{% trans "All" %}</a></li>
        {% for extension in settings_var.EXTENSIONS %}
            <li{% if query.filter_type == extension %} class="selected"{% endif %}><a href="{% query_string "" "filter_type,p" %}&amp;filter_type={{ extension }}">{% trans extension %}</a></li>
        {% endfor %}
    </ul>
</div>

filebrowser/templates/filebrowser/include/paginator.html
{% load i18n fb_tags %}
<p class="paginator">
    {% if query.q or query.filter_date or query.filter_type %}
    <span>{{ filelisting.results_current }} {% ifequal filelisting.results_current 1 %}{% trans 'result' %}{% else %}{% trans 'results' %}{% endifequal %}</span>
    {% endif %}

    {% if query.q or filelisting.results_total != filelisting.results_current %}
    <a href="{% query_string "" "filter_date,filter_type,p,q" %}" class="total">{{ filelisting.results_total }} {% trans 'total' %}</a>
    {% else %}
    <span>{{ filelisting.results_total }} {% trans "total" %}</span>
    {% endif %}

    {% if page_range %}
        {% for i in page_range %}
            {% ifequal i "." %}
                ...
            {% else %}
                {% ifequal i page_num %}
                    <span class="this-page">{{ i|add:"1" }}</span>
                {% else %}
                    <a href="{% query_string "" "p" %}&amp;p={{ i|add:"1" }}">{{ i|add:"1" }}</a>
                {% endifequal %}
            {% endifequal %}
        {% endfor %}
    {% endif %}
</p>